added styles for cart inital
inKEYYgnito/fsa-ecommerce-dogshopper pull request #34
Opened 2019-10-26 13:38 UTC by inKEYYgnito

@MariaSLapshina & @clacayetano  pls review. and make sure to pull changes from master every seconds. :D

2019-10-26 20:26 UTC, clacayetano commented on client/Components/App/App.jsx
>                  </>
why do we need props here?

2019-10-26 20:28 UTC, clacayetano requested changes

2019-10-26 20:28 UTC, clacayetano commented on client/Components/App/App.jsx
>                  </>
why do we need props here?

2019-10-27 15:51 UTC, MariaSLapshina approved these changes

2019-10-27 15:58 UTC, merged